// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"url-shortener/internal/config"
	"url-shortener/internal/delivery/http"
	"url-shortener/internal/delivery/http/middleware"
	"url-shortener/internal/delivery/http/route"
	"url-shortener/internal/repository"
	"url-shortener/internal/usecase"
	"url-shortener/internal/util"
)

// Injectors from injector.go:

func InitializedApp() *Application {
	viper := config.NewViper()
	logger := config.NewLogrus(viper)
	engine := config.NewGin(viper, logger)
	db := config.NewGorm(viper, logger)
	app := config.NewApp(engine, logger, viper, db)
	tokenUtil := util.NewTokenUtil(viper)
	redisClient := config.NewRedis(viper)
	authMiddleware := middleware.NewAuthMiddleware(tokenUtil, redisClient)
	userRepository := repository.NewUserRepository(db)
	transaction := util.NewTransaction(db)
	authUsecase := usecase.NewAuthUsecase(userRepository, transaction, tokenUtil, redisClient, logger)
	validate := config.NewValidator()
	authController := http.NewAuthController(authUsecase, validate, logger)
	urlRepository := repository.NewUrlRepository(db)
	urlUsecase := usecase.NewUrlUsecase(urlRepository, transaction, logger, redisClient)
	urlController := http.NewUrlController(urlUsecase, validate, logger)
	routeConfig := route.NewRouteConfig(engine, authMiddleware, authController, urlController)
	application := NewApplication(app, routeConfig)
	return application
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, usecase.NewAuthUsecase, http.NewAuthController)

var urlSet = wire.NewSet(repository.NewUrlRepository, usecase.NewUrlUsecase, http.NewUrlController)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

var routeSet = wire.NewSet(route.NewRouteConfig)
